language: python
python:
  - "3.7"

before_install:
  - R -e 'install.packages(c( "rmarkdown"), repos = "http://cran.us.r-project.org")'

before_script:
  # Install Packrat 
  - snakemake packrat_install
  - snakemake packrat_init
  - snakemake packrat_restore

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file environment.yml
  - conda activate test-environment

services: 
  - mysql

script:
  - cp -r tests/data/raw/* data/raw
  - snakemake --profile tests/settings -R sensor_features
  - ./env/bin/python -m unittest discover tests/scripts/ -v