# Participants to include in the analysis
# You must create a file for each participant named pXXX containing their device_id. This can be done manually or automatically
PIDS: [t01,t02]

# Global var with common day segments
DAY_SEGMENTS: &day_segments
  TYPE: INTERVAL_EVERY_DAY # FREQUENCY_EVERY_DAY, INTERVAL_EVERY_DAY, INTERVAL_FLEXIBLE_DAY
  FILE: "data/external/daysegments_interval.csv"

# Global timezone
# Use codes from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# Double check your code, for example EST is not US Eastern Time.
TIMEZONE: &timezone
  America/New_York

DATABASE_GROUP: &database_group
  MY_GROUP

DOWNLOAD_PARTICIPANTS:
  IGNORED_DEVICE_IDS: [] # for example "5a1dd68c-6cd1-48fe-ae1e-14344ac5215f"
  GROUP: *database_group

# Download data config
DOWNLOAD_DATASET:
  GROUP: *database_group

# Readable datetime config
READABLE_DATETIME:
  FIXED_TIMEZONE: *timezone

PHONE_VALID_SENSED_BINS:
  COMPUTE: False # This flag is automatically ignored (set to True) if you are extracting PHONE_VALID_SENSED_DAYS or screen or Barnett's location features
  BIN_SIZE: &bin_size 5 # (in minutes)
  # Add as many sensor tables as you have, they all improve the computation of PHONE_VALID_SENSED_BINS and PHONE_VALID_SENSED_DAYS. 
  # If you are extracting screen or Barnett's location features, screen and locations tables are mandatory.
  DB_TABLES: []

PHONE_VALID_SENSED_DAYS:
  COMPUTE: False
  MIN_VALID_HOURS_PER_DAY: &min_valid_hours_per_day [16] # (out of 24) MIN_HOURS_PER_DAY
  MIN_VALID_BINS_PER_HOUR: &min_valid_bins_per_hour [6] # (out of 60min/BIN_SIZE bins)

# Communication SMS features config, TYPES and FEATURES keys need to match
MESSAGES:
  DB_TABLE: messages
  PROVIDERS:
    RAPIDS:
      COMPUTE: False
      MESSAGES_TYPES : [received, sent]
      FEATURES: 
        received: [count, distinctcontacts, timefirstmessage, timelastmessage, countmostfrequentcontact]
        sent: [count, distinctcontacts, timefirstmessage, timelastmessage, countmostfrequentcontact]
      SRC_LANGUAGE: "r"
      SRC_FOLDER: "rapids" # inside src/features/messages

# Communication call features config, TYPES and FEATURES keys need to match
CALLS:
  DB_TABLE: calls
  PROVIDERS:
    RAPIDS:
      COMPUTE: False
      CALL_TYPES: [missed, incoming, outgoing]
      FEATURES:
        missed:  [count, distinctcontacts, timefirstcall, timelastcall, countmostfrequentcontact]
        incoming: [count, distinctcontacts, meanduration, sumduration, minduration, maxduration, stdduration, modeduration, entropyduration, timefirstcall, timelastcall, countmostfrequentcontact]
        outgoing: [count, distinctcontacts, meanduration, sumduration, minduration, maxduration, stdduration, modeduration, entropyduration, timefirstcall, timelastcall, countmostfrequentcontact]
      SRC_LANGUAGE: "r"
      SRC_FOLDER: "rapids" # inside src/features/calls

APPLICATION_GENRES:
  CATALOGUE_SOURCE: FILE # FILE (genres are read from CATALOGUE_FILE) or GOOGLE (genres are scrapped from the Play Store)
  CATALOGUE_FILE: "data/external/stachl_application_genre_catalogue.csv"
  UPDATE_CATALOGUE_FILE: false # if CATALOGUE_SOURCE is equal to FILE, whether or not to update CATALOGUE_FILE, if CATALOGUE_SOURCE is equal to GOOGLE all scraped genres will be saved to CATALOGUE_FILE
  SCRAPE_MISSING_GENRES: false # whether or not to scrape missing genres, only effective if CATALOGUE_SOURCE is equal to FILE. If CATALOGUE_SOURCE is equal to GOOGLE, all genres are scraped anyway

LOCATIONS:
  DB_TABLE: locations
  LOCATIONS_TO_USE: FUSED_RESAMPLED # ALL, GPS OR FUSED_RESAMPLED  
  FUSED_RESAMPLED_CONSECUTIVE_THRESHOLD: 30 # minutes, only replicate location samples to the next sensed bin if the phone did not stop collecting data for more than this threshold
  FUSED_RESAMPLED_TIME_SINCE_VALID_LOCATION: 720 # minutes, only replicate location samples to consecutive sensed bins if they were logged within this threshold after a valid location row
  TIMEZONE: *timezone
  PROVIDERS:
    DORYAB:
      COMPUTE: False
      FEATURES: ["locationvariance","loglocationvariance","totaldistance","averagespeed","varspeed","circadianmovement","numberofsignificantplaces","numberlocationtransitions","radiusgyration","timeattop1location","timeattop2location","timeattop3location","movingtostaticratio","outlierstimepercent","maxlengthstayatclusters","minlengthstayatclusters","meanlengthstayatclusters","stdlengthstayatclusters","locationentropy","normalizedlocationentropy"]
      DBSCAN_EPS: 10 # meters
      DBSCAN_MINSAMPLES: 5
      THRESHOLD_STATIC : 1 # km/h
      MAXIMUM_GAP_ALLOWED: 300
      MINUTES_DATA_USED: False
      SAMPLING_FREQUENCY: 0
      SRC_FOLDER: "doryab" # inside src/features/locations
      SRC_LANGUAGE: "python"

    BARNETT:
      COMPUTE: False
      FEATURES: ["hometime","disttravelled","rog","maxdiam","maxhomedist","siglocsvisited","avgflightlen","stdflightlen","avgflightdur","stdflightdur","probpause","siglocentropy","circdnrtn","wkenddayrtn"]
      ACCURACY_LIMIT: 51 # meters, drops location coordinates with an accuracy higher than this. This number means there's a 68% probability the true location is within this radius
      TIMEZONE: *timezone
      MINUTES_DATA_USED: False # Use this for quality control purposes, how many minutes of data (location coordinates gruped by minute) were used to compute features
      SRC_FOLDER: "barnett" # inside src/features/locations
      SRC_LANGUAGE: "r"

BLUETOOTH:
  DB_TABLE: bluetooth
  PROVIDERS:
    RAPIDS:
      COMPUTE: False
      FEATURES: ["countscans", "uniquedevices", "countscansmostuniquedevice"]
      SRC_FOLDER: "rapids" # inside src/features/bluetooth
      SRC_LANGUAGE: "r"


ACTIVITY_RECOGNITION:
  COMPUTE: False
  DB_TABLE: 
    ANDROID: plugin_google_activity_recognition
    IOS: plugin_ios_activity_recognition
  DAY_SEGMENTS: *day_segments
  FEATURES: ["count","mostcommonactivity","countuniqueactivities","activitychangecount","sumstationary","summobile","sumvehicle"]

BATTERY:
  COMPUTE: False
  DB_TABLE: battery
  DAY_SEGMENTS: *day_segments
  FEATURES: ["countdischarge", "sumdurationdischarge", "countcharge", "sumdurationcharge", "avgconsumptionrate", "maxconsumptionrate"]

SCREEN:
  COMPUTE: False
  DB_TABLE: screen
  DAY_SEGMENTS: *day_segments
  REFERENCE_HOUR_FIRST_USE: 0
  IGNORE_EPISODES_SHORTER_THAN: 0 # in minutes, set to 0 to disable
  IGNORE_EPISODES_LONGER_THAN: 0 # in minutes, set to 0 to disable
  FEATURES_DELTAS: ["countepisode", "episodepersensedminutes", "sumduration", "maxduration", "minduration", "avgduration", "stdduration", "firstuseafter"]
  EPISODE_TYPES: ["unlock"]

LIGHT:
  DB_TABLE: light
  PROVIDERS:
    RAPIDS:
      COMPUTE: TRUE
      FEATURES: ["count", "maxlux", "minlux", "avglux", "medianlux", "stdlux"]
      SRC_FOLDER: "rapids" # inside src/features/light
      SRC_LANGUAGE: "python"


ACCELEROMETER:
  COMPUTE: False
  DB_TABLE: accelerometer
  DAY_SEGMENTS: *day_segments
  FEATURES:
    MAGNITUDE: ["maxmagnitude", "minmagnitude", "avgmagnitude", "medianmagnitude", "stdmagnitude"]
    EXERTIONAL_ACTIVITY_EPISODE: ["sumduration", "maxduration", "minduration", "avgduration", "medianduration", "stdduration"]
    NONEXERTIONAL_ACTIVITY_EPISODE: ["sumduration", "maxduration", "minduration", "avgduration", "medianduration", "stdduration"]
    VALID_SENSED_MINUTES: False

APPLICATIONS_FOREGROUND:
  DB_TABLE: applications_foreground
  PROVIDERS:
    RAPIDS:
      COMPUTE: TRUE
      SINGLE_CATEGORIES: ["all", "email"]
      MULTIPLE_CATEGORIES:
        social: ["socialnetworks", "socialmediatools"]
        entertainment: ["entertainment", "gamingknowledge", "gamingcasual", "gamingadventure", "gamingstrategy", "gamingtoolscommunity", "gamingroleplaying", "gamingaction", "gaminglogic", "gamingsports", "gamingsimulation"]
      SINGLE_APPS: ["top1global", "com.facebook.moments", "com.google.android.youtube", "com.twitter.android"] # There's no entropy for single apps
      EXCLUDED_CATEGORIES: []
      EXCLUDED_APPS: ["com.fitbit.FitbitMobile", "com.aware.plugin.upmc.cancer"]
      FEATURES: ["count", "timeoffirstuse", "timeoflastuse", "frequencyentropy"]
      SRC_FOLDER: "rapids" # inside src/features/applications_foreground
      SRC_LANGUAGE: "python"

HEARTRATE:
  COMPUTE: False
  DB_TABLE: fitbit_data
  DAY_SEGMENTS: *day_segments
  SUMMARY_FEATURES: ["restinghr"] # calories features' accuracy depend on the accuracy of the participants fitbit profile (e.g. heigh, weight) use with care: ["caloriesoutofrange", "caloriesfatburn", "caloriescardio", "caloriespeak"] 
  INTRADAY_FEATURES: ["maxhr", "minhr", "avghr", "medianhr", "modehr", "stdhr", "diffmaxmodehr", "diffminmodehr", "entropyhr", "minutesonoutofrangezone", "minutesonfatburnzone", "minutesoncardiozone", "minutesonpeakzone"]

STEP:
  COMPUTE: False
  DB_TABLE: fitbit_data
  DAY_SEGMENTS: *day_segments
  EXCLUDE_SLEEP:
    EXCLUDE: False
    TYPE: FIXED # FIXED OR FITBIT_BASED (CONFIGURE FITBIT's SLEEP DB_TABLE)
    FIXED:
      START: "23:00"
      END: "07:00"
  FEATURES:
    ALL_STEPS: ["sumallsteps", "maxallsteps", "minallsteps", "avgallsteps", "stdallsteps"]
    SEDENTARY_BOUT: ["countepisode", "sumduration", "maxduration", "minduration", "avgduration", "stdduration"]
    ACTIVE_BOUT: ["countepisode", "sumduration", "maxduration", "minduration", "avgduration", "stdduration"]
  THRESHOLD_ACTIVE_BOUT: 10 # steps
  INCLUDE_ZERO_STEP_ROWS: False

SLEEP:
  COMPUTE: False
  DB_TABLE: fitbit_data
  DAY_SEGMENTS: *day_segments
  SLEEP_TYPES: ["main", "nap", "all"]
  SUMMARY_FEATURES: ["sumdurationafterwakeup", "sumdurationasleep", "sumdurationawake", "sumdurationtofallasleep", "sumdurationinbed", "avgefficiency", "countepisode"]

WIFI:
  DB_TABLE: 
    VISIBLE_ACCESS_POINTS: "wifi" # if you only have a CONNECTED_ACCESS_POINTS table, set this value to ""
    CONNECTED_ACCESS_POINTS: "sensor_wifi" # if you only have a VISIBLE_ACCESS_POINTS table, set this value to ""
  PROVIDERS:
    RAPIDS:
      COMPUTE: False
      FEATURES: ["countscans", "uniquedevices", "countscansmostuniquedevice"]
      SRC_FOLDER: "rapids" # inside src/features/bluetooth
      SRC_LANGUAGE: "r"

CONVERSATION:
  DB_TABLE: 
    ANDROID: plugin_studentlife_audio_android
    IOS: plugin_studentlife_audio
  PROVIDERS:
    RAPIDS:
      COMPUTE: True
      FEATURES: ["minutessilence", "minutesnoise", "minutesvoice", "minutesunknown","sumconversationduration","avgconversationduration",
        "sdconversationduration","minconversationduration","maxconversationduration","timefirstconversation","timelastconversation","sumenergy",
        "avgenergy","sdenergy","minenergy","maxenergy","silencesensedfraction","noisesensedfraction",
        "voicesensedfraction","unknownsensedfraction","silenceexpectedfraction","noiseexpectedfraction","voiceexpectedfraction",
        "unknownexpectedfraction","countconversation"]
      RECORDING_MINUTES: 1
      PAUSED_MINUTES : 3
      SRC_FOLDER: "rapids" # inside src/features/conversation
      SRC_LANGUAGE: "python"

### Visualizations ################################################################
HEATMAP_FEATURES_CORRELATIONS:
  PLOT: False
  MIN_ROWS_RATIO: 0.5
  MIN_VALID_HOURS_PER_DAY: *min_valid_hours_per_day
  MIN_VALID_BINS_PER_HOUR: *min_valid_bins_per_hour
  PHONE_FEATURES: [accelerometer, activity_recognition, applications_foreground, battery, calls_incoming, calls_missed, calls_outgoing, conversation, light, location_doryab, messages_received, messages_sent, screen]
  FITBIT_FEATURES: [fitbit_heartrate, fitbit_step, fitbit_sleep]
  CORR_THRESHOLD: 0.1
  CORR_METHOD: "pearson" # choose from {"pearson", "kendall", "spearman"}

HISTOGRAM_VALID_SENSED_HOURS:
  PLOT: False
  MIN_VALID_HOURS_PER_DAY: *min_valid_hours_per_day
  MIN_VALID_BINS_PER_HOUR: *min_valid_bins_per_hour

HEATMAP_DAYS_BY_SENSORS:
  PLOT: False
  MIN_VALID_HOURS_PER_DAY: *min_valid_hours_per_day
  MIN_VALID_BINS_PER_HOUR: *min_valid_bins_per_hour
  EXPECTED_NUM_OF_DAYS: -1
  DB_TABLES: [accelerometer, applications_foreground, battery, bluetooth, calls, light, locations, messages, screen, wifi, sensor_wifi, plugin_google_activity_recognition, plugin_ios_activity_recognition, plugin_studentlife_audio_android, plugin_studentlife_audio]

HEATMAP_SENSED_BINS:
  PLOT: False
  BIN_SIZE: *bin_size

OVERALL_COMPLIANCE_HEATMAP:
  PLOT: False
  ONLY_SHOW_VALID_DAYS: False
  EXPECTED_NUM_OF_DAYS: -1
  BIN_SIZE: *bin_size
  MIN_VALID_HOURS_PER_DAY: *min_valid_hours_per_day
  MIN_VALID_BINS_PER_HOUR: *min_valid_bins_per_hour

