site_name: RAPIDS
# theme: 'material'
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - smarty
    - wikilinks
    - codehilite:
        linenums: True
    # - urlize # requires: pip install git+https://github.com/r0wb0t/markdown-urlize.git
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: True
    - pymdownx.tilde
    - attr_list
    - pymdownx.keys
site_favicon: material/air-filter
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/julio_ui'
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_name: 'carissalow/rapids'
repo_url: 'https://github.com/carissalow/rapids'
copyright: 'Released under AGPL'
theme:
  name: material
  palette:
    primary: blue
  icon:
    logo: material/air-filter
  features:
    - navigation.sections
    
nav:
  - Home: 'index.md'
  - Setup:
    - File Structure: file-structure.md
    - Installation: 'setup/installation.md'
    - Initial Configuration: setup/configuration.md
    - Execution: setup/execution.md
  - Example Workflows:
    - Minimal: workflow-examples/minimal.md
  - Behavioral Features:
      - Introduction: features/feature-introduction.md
      - Phone:
        - Phone Data Quality: features/phone-data-quality.md
        - Phone Accelerometer: features/phone-accelerometer.md
        - Phone Activity Recognition: features/phone-activity-recognition.md
        - Phone Applications Foreground: features/phone-applications-foreground.md
        - Phone Battery: features/phone-battery.md
        - Phone Bluetooth: features/phone-bluetooth.md
        - Phone Calls: features/phone-calls.md
        - Phone Conversation: features/phone-conversation.md
        - Phone Light: features/phone-light.md
        - Phone Locations: features/phone-locations.md
        - Phone Messages: features/phone-messages.md
        - Phone Screen: features/phone-screen.md
        - Phone WiFI Connected: features/phone-wifi-connected.md
        - Phone WiFI Visible: features/phone-wifi-visible.md
      - Add New Features: features/add-new-features.md
  - Developers:
    - Remote Support: developers/remote-support.md
    - Virtual Environments: developers/virtual-environments.md
    - Documentation: developers/documentation.md
    - Testing: developers/testing.md
    - Test cases: developers/test-cases.md
  - Frequently Asked Questions: faq.md
  - Team: team.md
  - Citation: citation.md
