site_name: RAPIDS
# theme: 'material'
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - smarty
    - wikilinks
    - codehilite:
        linenums: True
    # - urlize # requires: pip install git+https://github.com/r0wb0t/markdown-urlize.git
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: True
    - pymdownx.tilde
    - attr_list
site_favicon: material/air-filter
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/julio_ui'
repo_name: 'carissalow/rapids'
repo_url: 'https://github.com/carissalow/rapids'
copyright: 'Released under AGPL'
theme:
  name: material
  palette:
    primary: blue
  icon:
    logo: material/air-filter
  features:
    - navigation.sections
    
nav:
  - Home: 'index.md'
  - File Structure: file-structure.md
  - Setup:
    - Installation: 'setup/installation.md'
    - Initial Configuration: setup/configuration.md
    - Execution: setup/execution.md
  - Example Workflows:
    - Minimal: workflow-examples/minimal.md
  - Behavioral Features:
      - Introduction: features/feature-introduction.md
      - Phone:
        - Phone Data Quality: features/phone-data-quality.md
        - Phone Messages: features/phone-messages.md
        - Phone Calls: features/phone-calls.md
        - Phone Bluetooth: features/phone-bluetooth.md
        - Phone WiFI Visible: features/phone-wifi-visible.md
        - Phone WiFI Connected: features/phone-wifi-connected.md
  - Frequently Asked Questions: faq.md
