name: ci
on:
  push:
    branches:
      - day_segments
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install git+https://${GH_TOKEN}@github.com/carissalow/mkdocs-material-insiders.git
      - run: pip install mike
      - run: mike deploy --push --update-aliases 0.1 latest
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
